### PR TITLE
Added Shadow damage to item tests

### LINKED ISSUE #7: Shadow damage in Classic
I think AutoGear is assessing this wrong:

Here's it's logic:

Screen Shot 2020-02-11 at 9 29 49 PM

And here are the items:

Screen Shot 2020-02-11 at 9 30 02 PM

It doesn't appear the Shadow damage is being taken into account?

### PR DESCRIPTION
**Pull request by jamtur01**
I think this fixes #7 - updated results:

Screen Shot 2020-02-11 at 10 02 41 PM

I limited it to the `WARLOCK` class currently.

### CODE REVIEW

**Comment by jamtur01** [comment]
I am not sure why it's pulling in 9ae2d5a. I'll try to rebase.

**Comment by jamtur01** [comment]
Although it seems just to have my changes in there... Oh well GH. *shrugs*

**Comment by AlexFolland** [comment]
This is interesting and cool, but I think warlocks don't consider shadow spell damage to be equivalent to spell damage because they also use fire spell damage in almost equal amounts.  I've debated this idea with @Synthetikaryote for mage as well, since even a frost mage uses Flamestrike and Fire Blast, and a fire mage uses Cone Of Cold.  I think we may need some way to weigh school-specific damage types separately.

@Synthetikaryote What do you think of this PR?

**Comment by jamtur01** [comment]
@AlexFolland That's a good point. I didn't consider that. I definitely think it being skipped enitrely is wrong so weighted separately seems like a potential approach.

**Comment by Synthetikaryote** [comment]
Thanks.  Although I want to implement this properly, this is a benefit already.

**Pull request merged**
